AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31
Resources:
  ResumeVisitrosTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: resumeVisitors
      AttributeDefinitions:
        - AttributeName: visitorId
          AttributeType: N
      KeySchema:
        - AttributeName: visitorId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${StaticSiteBucket}/*"

  getVisitorFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: it returns visitor count
      CodeUri: backend/getVisitor/
      Handler: get-visitor.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          FRONTEND_URL: !GetAtt StaticSiteBucket.WebsiteURL
      Events:
        GetVisitorApi:
          Type: Api
          Properties:
            Path: /visitor
            Method: GET

  putVisitorFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Description: it returns visitor count
      CodeUri: backend/putVisitor/
      Handler: put-visitor.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          FRONTEND_URL: !GetAtt StaticSiteBucket.WebsiteURL
      Events:
        GetVisitorApi:
          Type: Api
          Properties:
            Path: /visitor
            Method: PUT

Outputs:
  WebsiteURL:
    Description: URL of the website
    Value:
      Fn::GetAtt:
        - StaticSiteBucket
        - WebsiteURL
  LocalStackWebEndpoint:
    Description: "Localstack API Gateway endpoint URL for Prod stage "
    Value: !Sub "http://${ServerlessRestApi}.execute-api.localhost.localstack.cloud:4566/Prod/"
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  S3BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref StaticSiteBucket
